services:
  spark-pipeline:
    build: .
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    working_dir: /app/src
    command:
      - spark-submit
      - --master
      - local[2]
      - --driver-memory
      - 4g
      - --conf
      - spark.sql.shuffle.partitions=8
      - main.py